travis:
  secure:
    BINSTAR_TOKEN: Oer4NZFOVmM1u5Bs24FNKKqtYttocyhpMwLhXLc50uTPXE4ez0gtVOLiGWd/lHj3F4iCl4bpVWVGzLP9gDb8fB0LA/JQz8YcAT0vqkCS1yUdZBrGtVbDtQcR3BaAVdA+VkPlC/eJ7Oio8V7I/YHVZRTWO4RA3tRfev/HHEJ/29Bm4q2uBf0GYHV2ulNU0TybvIfmXtYv6MitTYU32PRLqknN8f2mOkXrh5WnL0SFNzwjsXn1NF2bzxJ8GXW8DwuweSz8yiDiaUUx245ZbFBGonbV1z1uEMms96L+rs5/TzEp31I4JVch0+gIsz8t+n9lnrn3KDhRB/3f+FhyaSvowf6MuU8RqRXQLsPqfcSQCGQBXTnveqmtHhn+/cgnhyxQyukqPq6YeE6ZabzPBEjB2EbC2FhA+sC7/YBza74ZfBoiDsFGPHsHvE3AzP++KYjGT+r7uU5CrLJ7Do1HCKemquyY/fsiReX1YZy307lg/kP7kenUBtxU9qFYP4oPqqAl/M+E3OkhYiEPBa/Px/jX06SZ+XJVzO+zHYJukWfRhatSNzUTuJO9bY3cR8Uts0+dhowpJhpKNZ6x9gOMj51c58kJOJewcfFVyLCMFSvgIMMIwKYXW5d/r/DRmWqbcfEHcCKiG8X/l/3XYGj8UCzNjkdGoMiELEeFf3U6gIlwuCw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
